name: Fetch RSS Feeds

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch RSS Feeds
        run: |
          curl -X POST https://alpha-shares-info.vercel.app/api/fetch_rss
